### ISSUE TITLE
Propriedade css usado de forma incorreta

### ISSUE THREAD

**Issue by bruno3du** [JuniorVentura23/Projeto-Slidershow#1]
Eu vi que você usou a seguinte propriedade css, ```overflow-x: hidden;``` no entanto você comenteu dois erros. Primeiro escreveu desta forma: ```overflowX:hidden```, isso invalida a propriedade fazendo ele não funcionar. 

Segundo erro é o fato de usar ele em tudo, quando você faz isso:
```css
* {
    padding:0;
    margin:0;
    box-sizing:border-box;
    overflowX:hidden;
    text-decoration:none;
    list-style: none;
}
```

Você usa em todos os elementos, no entanto nem sempre você vai realmente esperar este comportamento, então neste caso, utilize esta propriedade apenas em elementos que é esperado isso.
